!*******1*********2*********3*********4*********5*********6*********7**
 
!  ****************
!  *              *
!  * f2d_comm.inc *
!  *              *
!  ****************
 
!+ FIT2D COMMunication
 
!  Description:
!    Important communication parameters
!  Keywords:
!  Method:
!    Common blocks
!  Deficiencies:
!  Bugs:
!  Authors:
!    A P Hammersley (hammersley@esrf.fr)
!  History:
!    23-Jun-1995: V0.1 Original (Hammersley)
!  Global Constants:
!    Global Variables:
     Integer :: f2d_ok
 
!  Common block for data data-base
     Common / F2D_COMMPARS / f2d_ok
 
!--------1---------2---------3---------4---------5---------6---------7--
 
!  End of f2d_comm.inc
!********1*********2*********3*********4*********5*********6*********7**
